# consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
# consul注册中心地址
  cloud:
    consul:
      host: 101.43.32.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

